version: '3.7'

services:
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "8080:80"
    volumes:
      - ./config/server/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - landing

  landing:
    build:
      dockerfile: ./config/server/landing.dockerfile
    volumes:
      - ./:/var/www/html

  activity:
    build:
      dockerfile: ./config/server/activity.dockerfile
    entrypoint: [ 'php', '/var/www/html/bin/console', 'messenger:consume', 'async','-vv' ]
    restart: always
    volumes:
      - ./:/var/www/html
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
